# Generated by Django 5.0.4 on 2024-04-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="customer",
            name="Place",
            field=models.CharField(max_length=20),
        ),
    ]
