# Generated by Django 5.0.4 on 2024-05-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buy_now",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("phone", models.CharField(max_length=10)),
                ("adress", models.TextField()),
                ("amount", models.CharField(max_length=100)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_buy",
                        to="sales_app.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("cvv", models.CharField(max_length=3)),
                ("expiry_date", models.CharField(max_length=10)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to="sales_app.cart",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
