# Generated by Django 5.0.4 on 2024-05-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0002_buy_now_pay_delete_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pay",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pay_buy",
                to="sales_app.buy_now",
            ),
        ),
    ]
