# Generated by Django 5.0.4 on 2024-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0003_alter_pay_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy_now",
            name="quantity",
            field=models.CharField(max_length=10),
        ),
    ]
