# Generated by Django 5.0.4 on 2024-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0004_alter_buy_now_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pay",
            old_name="cart",
            new_name="buy",
        ),
        migrations.AlterField(
            model_name="pay",
            name="card_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pay",
            name="cvv",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="pay",
            name="expiry_date",
            field=models.CharField(max_length=100),
        ),
    ]
