# Generated by Django 5.0.4 on 2024-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0005_rename_cart_pay_buy_alter_pay_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy_now",
            name="phone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="buy_now",
            name="quantity",
            field=models.CharField(max_length=100),
        ),
    ]
