# Generated by Django 5.0.4 on 2024-05-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0006_alter_buy_now_phone_alter_buy_now_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("subject", models.CharField(max_length=250)),
                ("feedback", models.TextField()),
                ("reply", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_customer",
                        to="sales_app.customer",
                    ),
                ),
            ],
        ),
    ]
